# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  - osx
julia:
  - 1.3
  - nightly
notifications:
  email: false
script:
  - julia -e 'using Pkg;
      Pkg.add(
        Pkg.PackageSpec(
          name="TensorOperations",
          url="https://github.com/ho-oto/TensorOperations.jl",
          rev="master"
        )
      );
      Pkg.build(; verbose = true);
      Pkg.test(coverage=true)'
jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg;
            Pkg.develop(PackageSpec(path=pwd()));
            Pkg.add(
              Pkg.PackageSpec(
                name="TensorOperations",
                url="https://github.com/ho-oto/TensorOperations.jl",
                rev="master"
              )
            );
            Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
